#aksauth
variables:
  - name: USER_ASSIGNED_CLIENT_ID
    value: 'a699272b-3aa5-439b-baae-6abec0abbcd6'
  - name: SERVICE_ACCOUNT_NAME
    value: 'kedasvc'
  - name: NAMESPACE_NAME
    value: 'keda113'
  - name: TENANT_ID
    value: '17a09c66-f406-4897-8b24-51f5313623dc'
trigger: none
pr: none
pool:
  vmImage: ubuntu-latest

jobs: 

  - job: aksdeploy
    displayName: AKSdepoy
    timeoutInMinutes: 3 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 2 # how much time to give 'run always even if cancelled tasks' before stopping them
    steps:
      - task: KubeloginInstaller@0
        inputs:
          kubeloginVersion: 'latest'
        displayName: installkubelogin
      
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'aks-svc-june22'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
           
            az aks get-credentials --resource-group testrg --name aks-cluster-1 
            kubelogin convert-kubeconfig -l azurecli
          
        
        displayName: 'Get AKS credentials'


      - script: |
              sed -i "s|#{SERVICE_ACCOUNT_NAME}#|$(SERVICE_ACCOUNT_NAME)|g" ./aksyamls/svc.yml
              sed -i "s|#{NAMESPACE_NAME}#|$(NAMESPACE_NAME)|g" ./aksyamls/namespace.yml
              sed -i "s|#{USER_ASSIGNED_CLIENT_ID}#|$(USER_ASSIGNED_CLIENT_ID)|g" ./aksyamls/svc.yml
        displayName: 'Replace variables Name in Manifest'

      - task: AzureCLI@2

        inputs:
          azureSubscription: 'aks-svc-june22'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            
            kubectl get pods 
            kubectl apply -f ./aksyamls/namespace.yml
            
        displayName: 'List AKS resources & create namespace'

      - task: AzureCLI@2

        inputs:
          azureSubscription: 'aks-svc-june22'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            
            kubectl apply -f ./aksyamls/svc.yml -n $(NAMESPACE_NAME)
            
        displayName: 'Create Service Account'

      - task: AzureCLI@2
        inputs:
          azureSubscription: 'aks-svc-june22'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            
            helm repo add kedacore https://kedacore.github.io/charts
            helm repo update
            
        displayName: 'helm repo add kedacore'

      - task: helmdeploy@1
        inputs:
          azureSubscription: 'aks-svc-june22'
          connectionType: 'Azure Resource Manager'
          azureResourceGroup: 'testrg'
          namespace: $(NAMESPACE_NAME)
          command: 'install'
          chartType: 'Name'
          chartName: 'kedacore/keda'
          releaseName: 'keda'
          overrideValues: |
            serviceAccount.create=false
            serviceAccount.name=$(SERVICE_ACCOUNT_NAME)
        
            podIdentity.azureworkloadIdentity.enabled=true
            podIdentity.azureworkloadIdentity.clientId=$(USER_ASSIGNED_CLIENT_ID)
            podIdentity.azureworkloadIdentity.tenantId=$(TENANT_ID)
        displayName: 'Install KEDA using Helm'
      

        
