apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: delta

  
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demoapp-svc
                port:
                  number: 80
