apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: delta
  
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: buzz.alwayslearn.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demoapp-svc
                port:
                  number: 80
