apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: delta
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: buzz.alwayslearn.in
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: demoapp-svc
            port:
              number: 80
 