apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-managed-prometheus-trigger-auth
  
spec:
  podIdentity:
      provider: azure-workload # use "azure" for pod identity and "azure-workload" for workload identity
      identityId: #{USER_ASSIGNED_CLIENT_ID}#  
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-managed-prometheus-scaler
  
spec:
  scaleTargetRef:
    name: demoapp
  minReplicaCount: 1
  maxReplicaCount: 20
  triggers:
  - type: prometheus
    metadata:
      serverAddress: https://monitor200-eehcexguhrfbfygs.eastus.prometheus.monitor.azure.com
      metricName: http_requests_total
      # query: sum(rate(http_requests_total{deployment="my-deployment"}[2m])) # Note: query must return a vector/scalar single element response
      # query: sum(increase(http_requests_total{deployment="my-deployment"}[1m]))
      query: sum(increase(nginx_ingress_controller_requests[5m]))

      threshold: '5'
      activationThreshold: '1'
    authenticationRef:
      name: azure-managed-prometheus-trigger-auth